# Generated by Django 5.2.17 on 2026-08-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationitem",
            name="label",
            field=models.CharField(
                help_text="Link text displayed in menu", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="navigationitem",
            name="url",
            field=models.CharField(
                help_text="Target URL or anchor (e.g. #portfolio)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(
                default="#B31942",
                help_text="Hex code for action buttons and accents (e.g. #B31942)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="auto_responder_message",
            field=models.TextField(
                default="Hi {name},\n\nThank you for requesting a quote for your {project_tier} project. We have received your request and will follow up within one business day.\n\n— MG Drywall USA",
                help_text="Email body sent to homeowners. Placeholders: {name}, {project_tier}, {phone}",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="auto_responder_subject",
            field=models.CharField(
                default="Thank you for contacting MG Drywall USA",
                help_text="Subject line for homeowner confirmation email",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="banner_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show announcement bar at the very top of the site",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="banner_link",
            field=models.CharField(
                blank=True,
                default="#lead-form",
                help_text="URL or anchor the banner links to",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="banner_text",
            field=models.CharField(
                blank=True,
                default="Free on-site estimates for all residential projects!",
                help_text="Text shown inside the announcement bar",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Browser tab icon (square, 32×32 or 64×64)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="google_review_url",
            field=models.URLField(
                blank=True, default="", help_text="Direct link to leave a Google Review"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="State contractor license number – rendered in trust badges",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Company logo (PNG or SVG recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="notification_emails",
            field=models.CharField(
                default="info@mgdrywallusa.com",
                help_text="Comma-separated emails to receive incoming quote requests",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                default="#0A3161",
                help_text="Hex code for primary brand color (e.g. #0A3161)",
                max_length=7,
            ),
        ),
    ]
