# Generated by Django 5.2.17 on 2026-09-14 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0003_settingspreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="accent_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_locality",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_region",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="banner_enabled",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="banner_link",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="banner_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="country",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="google_review_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="price_range",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="tagline",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="yelp_url",
        ),
        migrations.DeleteModel(
            name="NavigationItem",
        ),
    ]
