# Generated by Django 5.2.17 on 2026-09-14 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0004_remove_sitesettings_accent_color_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SettingsPreview",
        ),
    ]
