# Generated by Django 5.2.17 on 2026-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0005_delete_settingspreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="auto_responder_message",
            field=models.TextField(
                default="Hi {name},\n\nThank you for requesting a quote for your {project_tier} project. We have received your request and will follow up within one business day.\n\n— Your Business Name",
                help_text="Email body sent to homeowners. Placeholders: {name}, {project_tier}, {phone}",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="auto_responder_subject",
            field=models.CharField(
                default="Thank you for contacting us",
                help_text="Subject line for homeowner confirmation email",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="notification_emails",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated emails to receive incoming quote requests",
                max_length=500,
            ),
        ),
    ]
