# Generated by Django 5.2.17 on 2026-08-18 19:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_portfoliopage_remove_portfolioitem_image_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Brief project summary shown on the portfolio card (supports formatted text)",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main project image (800x600 or larger, will be cropped to fill)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitemimage",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Optional caption displayed below the gallery image",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitemimage",
            name="image",
            field=models.ForeignKey(
                help_text="Gallery image (800x600 or larger, will be cropped to fill)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
