# Generated by Django 5.2.17 on 2026-08-15 21:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homepage_lead_section_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("label", models.CharField(help_text="Link text displayed in menu", max_length=100)),
                ("url", models.CharField(help_text="Target URL or anchor (e.g. #portfolio)", max_length=255)),
                (
                    "setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_items",
                        to="home.sitesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
