# Generated by Django 5.2.17 on 2026-08-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_sitesettings_and_navigationitem"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="cta_primary_label",
            field=models.CharField(
                default="Get a Free Quote",
                help_text="Text for the primary action button",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_primary_url",
            field=models.CharField(
                default="#lead-form",
                help_text="Destination URL or anchor (e.g. '#lead-form' or '/contact')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_secondary_label",
            field=models.CharField(
                default="View Our Work",
                help_text="Text for the secondary action button",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_secondary_url",
            field=models.CharField(
                default="#portfolio",
                help_text="Destination URL or anchor (e.g. '#portfolio' or '/portfolio')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_heading",
            field=models.CharField(
                default="MG Drywall USA",
                help_text="Main headline displayed prominently (keep under 50 characters)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image for hero section (1920x1080 or larger, will be cropped to fill)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_kicker",
            field=models.CharField(
                blank=True,
                default="Trusted drywall professionals",
                help_text="Short label above the headline, e.g. 'Trusted drywall professionals'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subheading",
            field=models.TextField(
                blank=True,
                default="Professional drywall installation, repair, and finishing for residential and commercial projects.",
                help_text="Supporting text below the headline (1-2 sentences)",
            ),
        ),
        migrations.AlterField(
            model_name="homepageserviceitem",
            name="description",
            field=models.TextField(
                help_text="Brief service description (2-3 sentences, shown on the service card)"
            ),
        ),
        migrations.AlterField(
            model_name="homepageserviceitem",
            name="icon_name",
            field=models.CharField(
                blank=True,
                default="shield",
                help_text="Icon identifier. One of: wall, patch, paint, shield",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="homepageserviceitem",
            name="title",
            field=models.CharField(
                help_text="Service name displayed on the card (e.g. 'Level 5 Finishing')",
                max_length=150,
            ),
        ),
    ]
