# Generated by Django 5.2.17 on 2026-08-23 01:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_cta_primary_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name displayed on the card (e.g. 'Level 5 Finishing')",
                        max_length=150,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier derived from the service name",
                        unique=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief service description (2-3 sentences, shown on the service card)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="shield",
                        help_text="Icon identifier. One of: wall, patch, paint, shield",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this service from the public site without deleting it",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HomePageFeaturedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_services",
                        to="home.homepage",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Select a service to feature on the homepage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="home.service",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
