# Generated by Django 5.2.17 on 2026-09-14 15:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_homepageserviceitem"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="accent_color",
            field=models.CharField(
                default="#B31942", help_text="Hex code for action buttons and accents (e.g. #B31942)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="address_locality",
            field=models.CharField(blank=True, default="Austin", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="address_region",
            field=models.CharField(blank=True, default="TX", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_enabled",
            field=models.BooleanField(default=False, help_text="Show announcement bar at the very top of the site"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_link",
            field=models.CharField(
                blank=True, default="#lead-form", help_text="URL or anchor the banner links to", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_text",
            field=models.CharField(
                blank=True,
                default="Free on-site estimates for all residential projects!",
                help_text="Text shown inside the announcement bar",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(
                default="info@mgdrywallusa.com", help_text="Primary public contact email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="country",
            field=models.CharField(blank=True, default="US", max_length=10),
        ),
        migrations.AddField(
            model_name="homepage",
            name="facebook_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Browser tab icon (square, 32×32 or 64×64)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="google_review_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="instagram_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="State contractor license number – rendered in trust badges",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Company logo (PNG or SVG recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="phone_number",
            field=models.CharField(
                default="+1-555-DRYWALL", help_text="Primary public contact phone number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="postal_code",
            field=models.CharField(blank=True, default="78701", max_length=20),
        ),
        migrations.AddField(
            model_name="homepage",
            name="price_range",
            field=models.CharField(blank=True, default="$$", max_length=10),
        ),
        migrations.AddField(
            model_name="homepage",
            name="primary_color",
            field=models.CharField(
                default="#0A3161", help_text="Hex code for primary brand color (e.g. #0A3161)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="site_name",
            field=models.CharField(
                default="MG Drywall USA",
                help_text="Business name used across headers, footers, and SEO metadata",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tagline",
            field=models.TextField(
                blank=True,
                default="Professional drywall installation, repair, and finishing for residential and commercial projects across the nation.",
                help_text="Primary business tagline displayed in the footer",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="yelp_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="HomePageNavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("label", models.CharField(help_text="Link text displayed in menu", max_length=100)),
                ("url", models.CharField(help_text="Target URL or anchor (e.g. #services)", max_length=255)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="navigation_items", to="home.homepage"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
