# Generated by Django 5.2.17 on 2026-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_copy_site_settings_chrome_to_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="address_locality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="address_region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", help_text="Primary public contact email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_heading",
            field=models.CharField(
                default="Your Business Name",
                help_text="Main headline displayed prominently (keep under 50 characters)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_kicker",
            field=models.CharField(
                blank=True,
                default="Trusted local professionals",
                help_text="Short label above the headline, e.g. 'Trusted local professionals'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subheading",
            field=models.TextField(
                blank=True,
                default="Professional services delivered with care and craftsmanship.",
                help_text="Supporting text below the headline (1-2 sentences)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", help_text="Primary public contact phone number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_subheading",
            field=models.TextField(
                blank=True,
                default="Specialized services tailored to residential and commercial needs.",
                help_text="Subtitle instruction text below the services header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="site_name",
            field=models.CharField(
                default="Your Business Name",
                help_text="Business name used across headers, footers, and SEO metadata",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="tagline",
            field=models.TextField(
                blank=True, default="", help_text="Primary business tagline displayed in the footer"
            ),
        ),
    ]
