# Generated by Django 5.2.17 on 2026-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_homepage_address_locality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="business_schema_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated Schema.org types for the JSON-LD block, e.g. 'Electrician, HomeAndConstructionBusiness'. Leave empty for the generic default pair.",
                max_length=255,
            ),
        ),
    ]
